### ISSUE TITLE
Automate '.env' creation

### ISSUE THREAD

**Issue by AdiKsOnDev** [AdiKsOnDev/YouTranslate#7]
# Idea
If a user tries to run the script without making `.env`:
- Make an **input** in console asking for everything needed (i.e **API key**).
- Create a `.env` with everything in it

### ATTENTION
Please refer to `docs/CONTRIBUTING.md` before doing **anything.**

**Comment by WaterNewt** [comment]
Hey @AdiKsOnDev, I'm working on this issue right now.

**Comment by AdiKsOnDev** [comment]
Solved by @WaterNewt 

Thanks!
